version: '3.8'

services:
  backend:
    # depends_on:
    #   - db
      # - searxng
    image: ghcr.io/bpawnzz/backend:466fbb369ceb86eae1a19c7fa3d93c0a7dc2beca
    restart: always
    hostname: backend
    env_file:
      - .env
    environment:
      - SEARCH_PROVIDER=${SEARCH_PROVIDER:-searxng}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      - SERPER_API_KEY=${SERPER_API_KEY:-}
      - BING_API_KEY=${BING_API_KEY:-}
      - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://host.docker.internal:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME:-}
      - AZURE_API_KEY=${AZURE_API_KEY:-}
      - AZURE_API_BASE=${AZURE_API_BASE:-}
      - AZURE_API_VERSION=${AZURE_API_VERSION:-}
      - OPENAI_MODE=${OPENAI_MODE:-}
      - CUSTOM_MODEL=${CUSTOM_MODEL:-}
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://postgres:password@db:5432/postgres}
      - DB_ENABLED=${DB_ENABLED:-True}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-False}
      - REDIS_URL=${REDIS_URL:-}
      - ENABLE_LOCAL_MODELS=${ENABLE_LOCAL_MODELS:-True}
    labels:
      - traefik.enable=true
      - traefik.http.routers.farfalle-backend.rule=Host(`farfalle.2damoon.xyz`) && PathPrefix(`/api`)
      - traefik.http.routers.farfalle-backend.entrypoints=websecure
      - traefik.http.routers.farfalle-backend.tls.certresolver=letsencrypt
      - traefik.http.services.farfalle-backend.loadbalancer.server.port=8000
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://searxng:8080}
    entrypoint: >
      /bin/sh -c "
        cd /workspace/src/backend &&
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /workspace/src/backend
    networks:
      - caddy_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    depends_on:
      - backend
    image: ghcr.io/bpawnzz/frontend:466fbb369ceb86eae1a19c7fa3d93c0a7dc2beca
    hostname: frontend
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://farfalle.2damoon.xyz/api}
      - NEXT_PUBLIC_LOCAL_MODE_ENABLED=${NEXT_PUBLIC_LOCAL_MODE_ENABLED:-true}
      - NEXT_PUBLIC_PRO_MODE_ENABLED=${NEXT_PUBLIC_PRO_MODE_ENABLED:-true}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.farfalle.entrypoints=websecure"
      - "traefik.http.routers.farfalle.rule=Host(`farfalle.2damoon.xyz`)"
      - "traefik.http.routers.farfalle.tls.certresolver=letsencrypt"
      - "traefik.http.services.farfalle.loadbalancer.server.port=3000"
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app
          ignore:
            - node_modules/
    networks:
      - caddy_default

  # searxng:
  #   image: docker.io/searxng/searxng:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./searxng:/etc/searxng:rw
  #   networks:
  #     - caddy_default

  # db:
  #   image: postgres:15.2-alpine
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - caddy_default

volumes:
  db_volume:
networks:
  caddy_default:
    external: true